---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.2

suites:
  - name: chef13
    driver:
      require_chef_omnibus: 13.9.4
    run_list:
      - recipe[s3_cli::default]
    verifier:
      inspec_tests:
        - test/integration/default

  - name: chef14
    driver:
      require_chef_omnibus: 14.2.0
    run_list:
      - recipe[s3_cli::default]
    verifier:
      inspec_tests:
        - test/integration/default
